server:
  port: 8081
  servlet:
    context-path: /plat-base
com:
  alipay:
    sofa:
      rpc:
        rest-port: 12100
        bolt-port: 12200
      tracer:
        zipkin:
          enabled: true
          baseUrl: http://yf009.intdev.hxyd.tech:9411
wish:
  plat:
    idgeneration:
      url: 172.29.12.100:12200
    base:
      url: 127.0.0.1:12200
#db
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yf022.intdev.hxyd.tech:24801/base?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: base
    password: base
mybatis:
  mapper-locations: classpath:com/wish/plat/base/dao/mapper/xml/*.xml
#zipkin